name: genio_card
description: "A Genio Card Flutter App."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.6.1
  file_picker: ^8.1.4
  http: ^1.2.2
  firebase_core: ^3.8.1
  firebase_storage: ^12.3.7
  cloud_firestore: ^5.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_auth: ^5.3.4
  loading_animation_widget: ^1.3.0
  flutter_native_splash: ^2.4.3
  intl: ^0.20.1
  flutter_flip_card: ^0.0.6
  flutter_launcher_icons: ^0.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_native_splash:
  image: assets/images/GenioCardLogoV3.png
  android_12:
    image: assets/images/GenioCardLogoV3.png
  color: "#1B1C1D"
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/GenioCardLogo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
